//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_Development_Project : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Single LeftTriggerFloat
        {
            get
            {
                return SteamVR_Actions.development_Project_LeftTriggerFloat;
            }
        }
        
        public virtual SteamVR_Action_Single RightTriggerFloat
        {
            get
            {
                return SteamVR_Actions.development_Project_RightTriggerFloat;
            }
        }
        
        public virtual SteamVR_Action_Boolean RightTriggerBool
        {
            get
            {
                return SteamVR_Actions.development_Project_RightTriggerBool;
            }
        }
        
        public virtual SteamVR_Action_Boolean LeftTriggerBool
        {
            get
            {
                return SteamVR_Actions.development_Project_LeftTriggerBool;
            }
        }
    }
}
